### PR TITLE
media-libs/mesa: this version is dropped, 17.3.0 builds fine

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by InBetweenNames** [comment]
Is this confirmed to work with LTO using `nouveau`?

**Comment by soredake** [comment]
I'll re-testing build right now.

**Comment by soredake** [comment]
Yes, it builds fine.

**Comment by InBetweenNames** [comment]
Looks good -- I just tested it myself as well.  Could we perhaps amend this to apply to all versions below 17.3.0 instead of removing it outright?

**Comment by soredake** [comment]
17.2.6 build fine.

**Comment by InBetweenNames** [comment]
Great, thanks!

**Pull request merged**
