### PR TITLE
dev-libs/wayland needs lto disabled

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by InBetweenNames** [comment]
Cannot reproduce.  Can you provide a build log?  Also, are you using the `gcc-config` from this overlay?

**Comment by soredake** [comment]
>are you using the gcc-config from this overlay

Yes.

[buildlog.zip](https://github.com/InBetweenNames/gentooLTO/files/1553276/buildlog.zip)

**Comment by InBetweenNames** [comment]
Ahh yes, I see it.  You're using wayland `1.13.0`.  It appears the problem is fixed in `1.14.0`.  I'll accept this PR if it is amended to be `<dev-libs/wayland-1.14.0 *FLAGS-=-flto*`

**Comment by soredake** [comment]
1.14.0 fails too, 9999 is not.

**Comment by InBetweenNames** [comment]
1.14.0 fails?  Can I get a build.log of that?  \

**Comment by soredake** [comment]
Sure.
[buildlog-1-14-0.zip](https://github.com/InBetweenNames/gentooLTO/files/1553361/buildlog-1-14-0.zip)

**Comment by InBetweenNames** [comment]
Can you re-emerge `ltoize` and try it again?  We have a patch in `/etc/patches` for this, and I think it's possible the symlink hasn't been updated on your system.

**Comment by soredake** [comment]
No revbump (better to do them on patch add) on the ebuild, that's why i don't get the patch.

**Comment by InBetweenNames** [comment]
I'll make that a policy for new PRs -- did the patch work for you?

**Comment by soredake** [comment]
Yes, it build, thanks!

**Comment by InBetweenNames** [comment]
Thanks for the contribution!

**Pull request merged**
