### PR TITLE
sys-config/ltoize: update multi-thread patch for zstd-1.4.7

### LINKED ISSUE #663: LTOPatch fails to apply on app-arch/zstd-1.4.7
``` * ERROR: app-arch/zstd-1.4.7::gentoo failed (configure phase):
 *   patch -p1  failed with /var/db/repos/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch
 *
 * Call stack:
 *               ebuild.sh, line  762:  Called __ebuild_main 'configure'
 *      phase-functions.sh, line  970:  Called __source_all_bashrcs
 *               ebuild.sh, line  409:  Called __try_source '--no-qa' '/etc/portage/bashrc'
 *               ebuild.sh, line  458:  Called source '/etc/portage/bashrc'
 *                  bashrc, line    6:  Called BashrcdMain '/etc/portage/bashrc'
 *             environment, line  608:  Called LTOPatch
 *             environment, line 1275:  Called eapply '/var/db/repos/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *             environment, line 1851:  Called _eapply_patch '/var/db/repos/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *             environment, line 1789:  Called __helpers_die 'patch -p1  failed with /var/db/repos/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *   isolated-functions.sh, line  112:  Called die
```

### PR DESCRIPTION
**Pull request by thrifty-txt**
Closes #663, should allow old versions of zstd to compile properly but will require updates in the future when the package is updated to ensure patch is applied. If there's a different way you want the patch folders formatted let me know.

### CODE REVIEW

**Comment by telans** [comment]
https://github.com/InBetweenNames/gentooLTO/pull/664
https://github.com/InBetweenNames/gentooLTO/pull/665

I guess they beat you to it

**Comment by thrifty-txt** [comment]
respect to the others but i'm different

**Comment by pchome** [comment]
Use something like `app-arch/zstd *FLAGS+="-DZSTDCLI_NBTHREADS_DEFAULT=0"` then.

**Comment by leonardohn** [comment]
This patch shouldn't be necessary anymore, now that they added an environment variable to set the default number of threads.

**Comment by telans** [comment]
It's needed to fix the other patch applying, but it shouldn't be updated after that

**Comment by thrifty-txt** [comment]
Thanks for pointing that out @pchome, I've updated the PR.

**Comment by InBetweenNames** [comment]
Thanks for this!  This issue was fixed via 288c09c4844c778848cc3016611ebf64e6b80e2a

**Pull request closed without merging**
