### PR TITLE
LTO config and workarounds touchup and two new workarounds

### PR DESCRIPTION
**Pull request by elsandosgrande**
1. Regarding the description of c9bb8e4, I was very sleepy when I wrote that, so my logic was flawed (I realize that using ${LTO} would not prevent a setup using `-fwhole-program` from working) and, ironically, that was one of the only workarounds not embedding a string within a string.
2. I know that this is a lot of changes at once, but by the time I realized that it is too much, there was no going back, as stashing commits is not a thing (or at least didn't work for me if it is a thing).

### CODE REVIEW

**Comment by wolfwood** [comment]
@elsandosgrande you can make feature branches based on develop and then git cherry-pick commits into the feature branches and make individual Pull Requests from each branch.

**Comment by elsandosgrande** [comment]
@wolfwood Tried before, but never got it to work properly. Also, do you know how to get rid of commits which were already accepted in previous pull requests (anything before c9bb8e4)? I have never had this issue in the Olive repository.

**Comment by wolfwood** [comment]
merge master into this branch. or to really clean up, rebase this branch onto master, which will let you squash commits, etc. but since it edits history you'll need to force push.

**Comment by elsandosgrande** [comment]
@wolfwood 
This *is* master though (my master, but still...). I tried to rebase, but I just got a lot of conflicts, mostly due to deleted files. I have tried `git rebase upstream/master --rebase-merges`, but `git status` reports nothing.

~~~ bash
sandy@sandys-pavilion:/opt/gentooLTO$ git rebase upstream/master --rebase-merges
Successfully rebased and updated refs/heads/master.
sandy@sandys-pavilion:/opt/gentooLTO$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
sandy@sandys-pavilion:/opt/gentooLTO$ git push
QSocketNotifier: Can only be used with threads started with QThread
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
QSocketNotifier: Can only be used with threads started with QThread
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
Everything up-to-date
sandy@sandys-pavilion:/opt/gentooLTO$ git push --force
QSocketNotifier: Can only be used with threads started with QThread
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
QSocketNotifier: Can only be used with threads started with QThread
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
Everything up-to-date
~~~

**Comment by InBetweenNames** [comment]
I largely agree with these changes -- there's no real need to have environment variables for single flag workarounds like `-fno-common`.  The only thing is renaming `FLTO` to `LTO` could break some peoples setups... but that's fixable with a news bulletin.

**Comment by elsandosgrande** [comment]
I was actually thinking of mentioning the possibility of a news item.

Hm... @InBetweenNames, I have an idea. Give me a minute.

**Comment by elsandosgrande** [comment]
There, that should cover it.

**Comment by elsandosgrande** [comment]
>  elsandosgrande authored and InBetweenNames committed on Jul 4, 2019 

Hm... In Olive, it lists my commits separately. Then again, Matthew set a "company" up on GitHub for Olive, while this is merely a personal repository. @wolfwood, regarding our earlier conversation, do you know if it is possible to replicate the behavior in another person's repository? I am not sure how to even formulate a search term for this...

**Comment by wolfwood** [comment]
@elsandosgrande

brute force approach:

git checkout -b stuff-sandy-likes master
git branch -D master
git checkout -b master origin/master
git checkout -b new-pull master
git cherry-pick *commit ids you want from stuff-sandy-likes*
git push new-pull origin/new-pull

**Comment by elsandosgrande** [comment]
All right, I will try making a new pull with that (I will keep this one opened just in case that the new one ends up being the exact same as this one). Shane, have mercy on me!

That still leaves me wondering "Why do commits from merged requests from people to this repository not appear as committed by them in the commit log, but merely as authored by them when they do not appear as such in Olive's repository?".

**Comment by wolfwood** [comment]
ah, the problem is that you already pushed you local master to origin/master, which is your GitHub fork, not this repository.

`git remote add` this repository's url with a different name than origin, i call mine upstream.

remake your local master branch from upstream/master instead. (if you set it tracking, `git pull`s will automatically come from upstream rather than origin) then you should be good to make new-pull2 and cherry pick

or should be able to just rebase stuff-sandy-likes (or perhaps  stuff-sandy-likes-copy) onto upstream/master

**Comment by elsandosgrande** [comment]
1. It is incomplete because there are no changes, that is the commit is "empty", at least as far as I can tell.
2. So... I just replace `origin` with `upstream` in the third command? All right (I already just deleted everything in the folder and cloned my fork).
3. Um... What about my other question (right above "**Edit**")?

**Comment by elsandosgrande** [comment]
So... @wolfwood, `new-pull` is only showing six commits in the difference now! I have already made it the new default branch and will proceed to delete `master` (rebasing just gives me errors, like before, `new-pull` already has the six new commits and I don't have the time to try to fight with `git rebase` for the exact commit history seeing as I failed last time) and subsequently rename `new-pull` to `master`, at which point I will make a new pull request.

@InBetweenNames, I have finally succeeded with the help of wolfwood!

**Comment by wolfwood** [comment]
@elsandosgrande you don't need to make a pull request from master. you can just push new-pull and make a PR from that, or any other branch.

regarding your other question, your author status maybe be because you have write access to Olive but not here, but i don't really know.

**Comment by elsandosgrande** [comment]
@wolfwood 

1. I wanted to make `new-pull` into `master`, but rebasing did not work, so I had to make `new-pull` default, then delete `master` and then finally rename `new-pull` to `master`. My guess is that this pull request would not like that. And yes, I know that I can make a pull request from any branch, but `new-pull` already has **all** of the commits *and* is already clean, so...
2. I do not, I merely made pull requests like here, the only difference being that `olive-editor` is an "organization", with `olive` being one of its repositories, while `InBetweenNames` is a user, with `gentooLTO` being one of his repositories (tl;dr organizational versus personal).

**Pull request closed without merging**
