### PR TITLE
sci-libs/scipy media-libs/dav1d: upstream isl update fixes graphite ice

### PR DESCRIPTION
**Pull request by wolfwood**
no more ICE, no more need for patches.

### CODE REVIEW

**Comment by elsandosgrande** [comment]
So that's why I got a GCC update... I guess?

**Comment by wolfwood** [comment]
@elsandosgrande recompiling isl alone fixed the issue for me. gcc revision bump must have been something else.

**Comment by elsandosgrande** [comment]
Oh. Pardon me for bothering you in that case!

**Comment by InBetweenNames** [comment]
Thank you!

**Pull request merged**
