### PR TITLE
sci-libs/scipy: graphite ICE

### PR DESCRIPTION
**Pull request by wolfwood**
temporary workaround for #450

### CODE REVIEW

**Comment by elsandosgrande** [comment]
@wolfwood Only removing the `-floop-nest-optimize` flag is necessary.

**Comment by wolfwood** [comment]
@InBetweenNames this patch should also include modifying the ltoize ebuild dependency to >=app-portage/portage-bashrc-mv-19.0, as the F*FLAGS syntax was just introduced, but I wasn't sure if you'd want to do a revision bump or what.

**Comment by InBetweenNames** [comment]
Ah yes, you're right.  After I'm done marking exams I'll make sure this and the graphite patch are merged, and the dependency on portage-bashrc-mv-19.0 or higher is added to ltoize.

**Comment by wolfwood** [comment]
@elsandosgrande you are correct. patched.

**Comment by wolfwood** [comment]
@InBetweenNames I figured it was that time of year; no rush.

**Comment by elsandosgrande** [comment]
Also, [from what I know](https://github.blog/2013-01-22-closing-issues-via-commit-messages/), you can automatically close the aforementioned ticket if you add "Fixes #blahblah" or "Closes #blahblah" or a few other possible keywords to either a commit which is covered by the pull request or to the very pull request's description itself (this part is mostly me guessing, since I have only seen it done like this once).

**Comment by wolfwood** [comment]
@InBetweenNames trofi just merged a pre-release patch for isl that fixes this issue today, lol.

**Pull request merged**
