### PR TITLE
dev-util/colm: disable remove-la from portage-bashrc-mv

### LINKED ISSUE #690: remove-la breaks colm and ragel
dev-util/colm-0.14.6 fails to build but works with noflto
but then
dev-util/ragel-7.0.3 fails to build needing libfsm.la

removing the remove-la flag both packs build fine

### PR DESCRIPTION
**Pull request by petronio**
Fixes #690

If you're having a dependency issue while attempting to rebuild it, first try downgrading colm and then updating ragel (pulls in newer colm).

### CODE REVIEW

**Comment by telans** [comment]
Could you rebase and maybe make a new file such as `bashrc-mv.conf` for general overrides?

**Comment by petronio** [comment]
> Could you rebase and maybe make a new file such as `bashrc-mv.conf` for general overrides?

Done

**Comment by InBetweenNames** [comment]
Although, I don't condone `remove-la` in general, this makes sense to me.  Thanks!

**Comment by thesamesam** [comment]
@InBetweenNames Could we consider turning it off in general using this flag? Upstream in Gentoo, we should strip it from ebuilds if it doesn't cause breakage.

I don't think a lot of users realise that portage-bashrc-mv does this by default (I didn't until recently!)

**Pull request merged**
