### PR TITLE
clang: more workarounds

### PR DESCRIPTION
**Pull request by telans**

### CODE REVIEW

**Comment by perfect7gentleman** [comment]
```
media-libs/dav1d-0.8.2::gentoo was built with the following:
USE="8bit asm -10bit"
CFLAGS="-march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -fforce-emit-vtables -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fstrict-vtable-pointers -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-standalone-debug -fno-unwind-tables"
CXXFLAGS="-march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -fforce-emit-vtables -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fstrict-vtable-pointers -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-standalone-debug -fno-unwind-tables -stdlib=libc++"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,--lto-O3 -Wl,--thinlto-jobs=9 -Wl,-z,norelro -fuse-ld=lld -stdlib=libc++ -rtlib=compiler-rt -unwindlib=libunwind -s -march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -fforce-emit-vtables -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fstrict-vtable-pointers -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-standalone-debug -fno-unwind-tables"
```

**Comment by telans** [comment]
@perfect7gentleman see https://github.com/InBetweenNames/gentooLTO/pull/707

The file isn't installed in current ebuild for some reason

**Comment by telans** [comment]
Are you saying it you don't get a general protection fault?

**Comment by perfect7gentleman** [comment]
No. You have these errors 'cause you're doing it wrong.

**Comment by telans** [comment]
Well the dav1d developer in the issue linked certainly has the issue and/or knows why it occurs, so it's not just a me issue

https://code.videolan.org/videolan/dav1d/-/issues/362

**Comment by perfect7gentleman** [comment]
Honestly, I don't care as I don't you this overlay as most of workarounds are incorrect and/or excessive.

**Comment by telans** [comment]
Well please enlighten me as to how I'm doing it wrong

```
CFLAGS="-march=znver2 -O3 -flto=thin -pipe"
CXXFLAGS="-march=znver2 -O3 -flto=thin -pipe"
LDFLAGS="-Wl,-O3 -Wl,--as-needed"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

[ebuild   R   *] sys-devel/llvm-12.0.0_rc2:12::gentoo  USE="gold libffi ncurses -debug -doc -exegesis -libedit -test -xar -xml -z3" ABI_X86="(64) -32 (-x32)" LLVM_TARGETS="AMDGPU BPF NVPTX (X86) -AArch64 -ARC -ARM -AVR (-CSKY) -Hexagon -Lanai -MSP430 -Mips -PowerPC -RISCV -Sparc -SystemZ -VE -WebAssembly -XCore" 0 KiB
[ebuild   R   *] sys-libs/llvm-libunwind-12.0.0_rc2::gentoo  USE="-debug -static-libs -test" ABI_X86="32 (64) (-x32)" 0 KiB
[ebuild   R   *] sys-devel/lld-12.0.0_rc2::gentoo  USE="-test" 0 KiB
[ebuild   R   *] sys-libs/libcxxabi-12.0.0_rc2::gentoo  USE="libunwind -static-libs -test" ABI_X86="32 (64) (-x32)" 0 KiB
[ebuild   R   *] sys-libs/libcxx-12.0.0_rc2::gentoo  USE="(libcxxabi) libunwind -static-libs -test" ABI_X86="32 (64) (-x32)" 0 KiB
[ebuild   R   *] sys-devel/clang-12.0.0_rc2-r1:12::gentoo [12.0.0_rc2:12::gentoo] USE="default-compiler-rt default-libcxx default-lld static-analyzer xml -debug -doc -test" ABI_X86="(64) -32 (-x32)" LLVM_TARGETS="AMDGPU BPF NVPTX (X86) -AArch64 -ARC -ARM -AVR (-CSKY) -Hexagon -Lanai -MSP430 -Mips -PowerPC -RISCV -Sparc -SystemZ -VE -WebAssembly -XCore" PYTHON_SINGLE_TARGET="python3_9 -python3_7 -python3_8" 0 KiB
[ebuild   R   *] sys-libs/compiler-rt-12.0.0_rc2:12.0.0::gentoo  USE="clang -test" 0 KiB
```

**Comment by perfect7gentleman** [comment]
first;y, read wiki.

**Comment by InBetweenNames** [comment]
@perfect7gentleman Just a reminder that this overlay has a code of conduct attached to it, available for reference here: https://github.com/InBetweenNames/gentooLTO/blob/master/.github/CODE_OF_CONDUCT.md , please don't hesitate to reach out to me if you have any questions about it.

With that out of the way, can you elaborate for other readers here what's wrong with this PR?  I don't have clang as my system compiler on any of my systems at the moment, so it'll take some time for me to delve into this.

**Comment by perfect7gentleman** [comment]
Most workarounds are unnecessary for Clang/LLVM. Imo, you'd better discard implementation of Clang/LLVM to your overlay.

**Comment by InBetweenNames** [comment]
I really welcome feedback on how we could make the Clang support in GentooLTO better, so thanks for chiming in.
The existing workarounds are installed for Clang simply because I haven't had time to validate what is applicable from the default GCC configuration and what isn't.  As of today there are only 3 explicit workarounds for Clang listed in `clang.conf`.  Is this what you're referring to?

**Comment by telans** [comment]
> Most workarounds are unnecessary for Clang/LLVM

Maybe referring to how all the GCC workarounds are applied?

I'll eventually get around to rebuilding my system wiout the GCC workarounds too and see what breaks, then find a way to disable GCC workarounds here when using Clang

**Comment by InBetweenNames** [comment]
Shouldn't be hard to do.  We could split off the workarounds into GCC and Clang ones.

**Comment by InBetweenNames** [comment]
Merging this despite not being able to test and despite the contradicting reports.  We can just go through the list later and figure out why certain things need workarounds with Clang.

**Pull request merged**
