### PR TITLE
sys-libs/libcap: use ld.bfd

### PR DESCRIPTION
**Pull request by jelinekto**
Issue #453

### CODE REVIEW

**Comment by elsandosgrande** [comment]
Maybe you should also add `*FLAGS-="-fuse-ld=gold"` in case somebody is using the same flag to enforce the usage of the Gold linker (I certainly can't be bothered to manage that through the `binutils` configuration).

**Comment by InBetweenNames** [comment]
Thank you!

**Comment by barolo** [comment]
@elsandosgrande You can't manage linkers through binutils-config any-longer it was removed very very recently

**Comment by elsandosgrande** [comment]
@barolo 

1. How recently (like, one month, two months, ...)?
2. Huh, I guess I chose the correct method when I stated using GentooLTO...
3. If I may ask, why do you never appear on Gitter?

**Comment by barolo** [comment]
@elsandosgrande
1. In last few updates, within last month, 5.2 no longer has that ability and I've seen post about it somewhere few days ago
2. Probably.
3. Do I have to? I'm not very social, it tires me easily. I just pop out from time to time.

**Comment by elsandosgrande** [comment]
@barolo 

1. Go figure. Out of curiosity, were the posts on the forums, or...?
2. Yay me!
3. Well, something tells me that somebody (most likely Shane) will lose their patience with conversations like these being held in tickets and requests instead of on Gitter, the **chat** client. I mean, that's the whole reason why I suggested it in the first place over half a year ago if memory serves.

**Comment by barolo** [comment]
@elsandosgrande 
1. https://forums.gentoo.org/viewtopic-t-1106116-start-0.html
3. Fine, seeing that gitter [ I know what it is ] have sensible irc bridges [ yeah I'm that guy ] I'll join

**Comment by elsandosgrande** [comment]
Well... I'm seventeen, so...

Also, why use an IRC bridge when I see that you have already logged into Gitter in the past at one point (I'm guessing that that was part of you checking it out; you are listed as one of the members of the group)? I mean, IRC does not maintain chat history, so...

**Pull request merged**
