### PR TITLE
media-libs/libwebp: gcc 9 fixed runtime issues caused by fipa-pta

### PR DESCRIPTION
**Pull request by asaparov**
Removed the workaround for this package. Is there a fixed section in the workarounds file?

### CODE REVIEW

**Comment by asaparov** [comment]
Nevermind... further testing revealed that this issue was not resolved.

**Comment by InBetweenNames** [comment]
Hey @asaparov are you saying `-fipa-pta` is still resulting in a runtime bug on this package?

**Comment by asaparov** [comment]
Yes, I tested with gcc 9 and it still causes the rendering issue for WebP images on firefox for me.

**Comment by InBetweenNames** [comment]
Is it using a system webp or one provided by Firefox?

**Comment by asaparov** [comment]
I was using the system webp.

**Comment by InBetweenNames** [comment]
I'll have to take a look.  No way I'm enabling -fipa-pta by default if
there are still runtime codegen errors with it.

**Comment by InBetweenNames** [comment]
Just rebuilt with `-fipa-pta` and it seems to be working correctly for me.  I'll rebuild firefox as well to see if maybe the culprit is in there.

**Comment by InBetweenNames** [comment]
Just rebuilt with `-fipa-pta` and it seems to be working correctly for me.  I also rebuilt Firefox and still can't seem to find any issues on my system.  What `USE` flags do you have enabled?  Here are mine:

~~~
gif jpeg opengl png tiff
~~~

**Comment by asaparov** [comment]
Yeah I have the same use flags on libwebp-1.0.2. But that is strange, I retested it again and I still get jumbled WebP images (usually all green or pink). I don't need to recompile firefox to reproduce it. Did you make sure to remove the workaround in ltoworkarounds.conf? And also to restart firefox with a fresh instance to make sure it loads the new libwebp library? I'm testing the WebP images at [fivethirtyeight.com](fivethirtyeight.com).

**Comment by barolo** [comment]
I can't reproduced this, I have full GLTO enabled on both and it's all fine. Could you provide some additional info about your system?

**Comment by asaparov** [comment]
Sure, my emerge --info is below. I'm not using LTO atm, but I am using graphite and Ofast.

```
Portage 2.3.66 (python 3.6.6-final-0, default/linux/amd64/17.0/desktop/plasma, gcc-9.1.0, glibc-2.29-r2, 5.1.0-gentoo x86_64)
=================================================================
System uname: Linux-5.1.0-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700HQ_CPU_@_2.60GHz-with-gentoo-2.6
KiB Mem:    16302096 total,  12315996 free
KiB Swap:    3999740 total,   3999740 free
Timestamp of repository gentoo: Sat, 11 May 2019 12:30:01 +0000
Head commit of repository gentoo: ee8272767fc844e42d178758e40fd5e93ad0dfb9
sh bash 4.4_p23-r1
ld GNU ld (Gentoo 2.32 p2) 2.32.0
ccache version 3.6 [disabled]
app-shells/bash:          4.4_p23-r1::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.26.2::gentoo
dev-lang/python:          2.7.15-r1::lto-overlay, 3.6.6-r1::lto-overlay
dev-util/ccache:          3.6::gentoo
dev-util/cmake:           3.14.3::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.41.2::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.16.1-r1::gentoo
sys-devel/binutils:       2.32-r1::gentoo
sys-devel/gcc:            9.1.0::lto-overlay
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.0-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r2::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-jobs: 1
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 24

4nykey
    location: /var/lib/layman/4nykey
    sync-type: laymansync
    sync-uri: https://github.com/4nykey/4nykey.git
    masters: gentoo
    priority: 50

java
    location: /var/lib/layman/java
    sync-type: laymansync
    sync-uri: git://anongit.gentoo.org/proj/java.git
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    sync-type: laymansync
    sync-uri: https://github.com/jorgicio/jorgicio-gentoo.git
    masters: gentoo
    priority: 50

lto-overlay
    location: /var/lib/layman/lto-overlay
    sync-type: laymansync
    sync-uri: https://github.com/InBetweenNames/gentooLTO.git
    masters: gentoo mv
    priority: 50

mv
    location: /var/lib/layman/mv
    sync-type: laymansync
    sync-uri: https://anongit.gentoo.org/git/user/mv.git
    masters: gentoo
    priority: 50

science
    location: /var/lib/layman/science
    sync-type: laymansync
    sync-uri: git://anongit.gentoo.org/proj/sci.git
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -Ofast -fgraphite-identity -floop-nest-optimize -ftree-loop-distribution -fipa-pta -fuse-linker-plugin -pipe -fno-stack-protector -feliminate-unused-debug-types -fno-semantic-interposition -falign-functions=32 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wl,--as-needed -Wl,-O1"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt /usr/share/sddm/scripts/Xsetup"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=native -Ofast -fgraphite-identity -floop-nest-optimize -ftree-loop-distribution -fipa-pta -fuse-linker-plugin -pipe -fno-stack-protector -feliminate-unused-debug-types -fno-semantic-interposition -falign-functions=32 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wl,--as-needed -Wl,-O1 -fvisibility-inlines-hidden"
DISTDIR="/usr/portage/distfiles"
EMERGE_DEFAULT_OPTS="--jobs=6 --load-average=6"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://lug.mtu.edu/gentoo ftp://lug.mtu.edu/gentoo rsync://mirrors.rit.edu/gentoo http://www.gtlib.gatech.edu/pub/gentoo rsync://rsync.gtlib.gatech.edu/gentoo ftp://ftp.gtlib.gatech.edu/pub/gentoo ftp://mirrors.rit.edu/gentoo/ http://mirrors.rit.edu/gentoo/"
LANG="en_US.utf8"
LDFLAGS="-Wl,--as-needed -Wl,--hash-style=gnu -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wl,-O1"
LINGUAS="en es zh_CN zh_TW ja ko"
MAKEOPTS="-j5 -l5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac aacplus acl acpi activities alsa amd64 avi bash_completion berkdb bluetooth branding bzip2 cairo cdda cdr cli colord consolekit crypt cups cxx dbus declarative dri dts dvd dvdr emboss encode exif faac faad fam fat flac fortran gd gdbm gif gimp glamor good gpm graphite gstreamer h264 hfs hpcups iconv ipv6 java jfs jpeg kde kipi kwallet latex lcms ldap libnotify libtirpc lm-sensors mad matroska mng mp3 mp4 mpeg ncurses networkmanager nls nptl ntfs3g ogg opencl opengl openmp pam pango pcre pdf pgo phonon plasma png policykit ppds pulseaudio qml qt5 readline reiser4 reiserfs samba scanner sdl seccomp semantic-desktop slp sna spell ssl startup-notification svg symlink tcpd threads thumbnail tiff touchpad truetype udev udisks ugly unicode upower usb vaapi vdpau vorbis vpx widgets wxwidgets x264 x265 xattr xcb xcomposite xfs xml xv xvid zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="synaptics evdev" KERNEL="linux" L10N="en es zh-CN zh-TW ja ko" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" NETBEANS_MODULES="apisupport cnd groovy gsf harness ide identity j2ee java mobility nb php profiler soa visualweb webcommon websvccommon xml" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-1" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" RUBY_TARGETS="ruby24" USERLAND="GNU" VIDEO_CARDS="nvidia intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

**Comment by barolo** [comment]
Did you try compiling it with O3 instead?

**Comment by asaparov** [comment]
I was able to reproduce it even when I recompiled libwebp with `CFLAGS="-O2 -pipe -march=native -fno-stack-protector -Wl,--as-needed -Wl,--hash-style=gnu -Wl,-O1"`, `CXXFLAGS="${CFLAGS}"`, and `LDFLAGS="-Wl,--as-needed -Wl,--hash-style=gnu -Wl,-O1"`. But I didn't try recompiling firefox with those less aggressive flags. But I can't think of how that would cause the problem.

**Comment by barolo** [comment]
Ofast is where you differ from us, AFAIK it disregards all standards compliances, that would be my bet.

**Comment by asaparov** [comment]
So after some tests, I found that -flto actually fixes this issue somehow. Even with my aggressive -Ofast flags, if I add -flto and recompile only libwebp, WebP images display correctly. However, removing -flto and recompiling libwebp, the images do not display correctly.

**Comment by barolo** [comment]
Still, I didn't have any issues with or without flto enabled webp. Smells unstable to me

**Comment by InBetweenNames** [comment]
No issues with libwebp for me yet either.  I'll do a more thorough check soon.

**Comment by asaparov** [comment]
@InBetweenNames Have you tried compiling libwebp without LTO?

**Comment by elsandosgrande** [comment]
@asaparov Have you tried not using `-Ofast` during compilation? I do not bother with compiling Firefox stable since I use Nightly anyway, so I am unfamiliar with the intricacies of Firefox compilation. And pardon me if I am mistaken, but I do not see any indication in the conversation thus far that you have attempted to use `-O3` in place of `-Ofast`.

**Comment by javashin** [comment]
is fine here too ::::: 
media-libs/libwebp-1.0.2::gentoo was built with the following:
USE="gif jpeg opengl png tiff (-neon) -static-libs -swap-16bit-csp" ABI_X86="32 (64) (-x32)" CPU_FLAGS_X86="sse2 sse4_1"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe"

**Comment by InBetweenNames** [comment]
@asaparov I haven't, but I will test it.

**Comment by asaparov** [comment]
@InBetweenNames yeah i tried, it didnt fix my issue =/
are you sure nightly is using the system libwebp?

**Pull request closed without merging**
